# Copyright (C) 2017 The Alcatel-msm8916 Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PATH_FILES := vendor/alcatel/alto45/proprietary

# Vendor
PRODUCT_COPY_FILES += \
$(PATH_FILES)/vendor/bin/audioflacapp:system/vendor/bin/audioflacapp \
$(PATH_FILES)/vendor/bin/tctd:system/vendor/bin/tctd \
$(PATH_FILES)/vendor/bin/tdc:system/vendor/bin/tdc

PRODUCT_COPY_FILES += \
$(PATH_FILES)/vendor/etc/audio_effects.conf:system/vendor/etc/audio_effects.conf \
$(PATH_FILES)/vendor/etc/calmodule.cfg:system/vendor/etc/calmodule.cfg

PRODUCT_COPY_FILES += \
$(PATH_FILES)/vendor/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd \
$(PATH_FILES)/vendor/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd

# DRM
PRODUCT_COPY_FILES += \
$(PATH_FILES)/vendor/lib/drm/libdrmprplugin.so:system/vendor/lib/drm/libdrmprplugin.so \
$(PATH_FILES)/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
$(PATH_FILES)/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so

# EGL
PRODUCT_COPY_FILES += \
$(PATH_FILES)/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
$(PATH_FILES)/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
$(PATH_FILES)/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
$(PATH_FILES)/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
$(PATH_FILES)/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so

PRODUCT_COPY_FILES += \
$(PATH_FILES)/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
$(PATH_FILES)/vendor/lib/hw/power.qcom.so:system/vendor/lib/hw/power.qcom.so

# SoundFX
PRODUCT_COPY_FILES += \
$(PATH_FILES)/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
$(PATH_FILES)/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
$(PATH_FILES)/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so

# Vendor/lib
PRODUCT_COPY_FILES += \
    $(PATH_FILES)/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    $(PATH_FILES)/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
    $(PATH_FILES)/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    $(PATH_FILES)/vendor/lib/libactuator_a3907.so:system/vendor/lib/libactuator_a3907.so \
    $(PATH_FILES)/vendor/lib/libactuator_a3907_camcorder.so:system/vendor/lib/libactuator_a3907_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_a3907_camera.so:system/vendor/lib/libactuator_a3907_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9714.so:system/vendor/lib/libactuator_dw9714.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9714_13p1ba.so:system/vendor/lib/libactuator_dw9714_13p1ba.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9714_13p1ba_camcorder.so:system/vendor/lib/libactuator_dw9714_13p1ba_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9714_13p1ba_camera.so:system/vendor/lib/libactuator_dw9714_13p1ba_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9714_camcorder.so:system/vendor/lib/libactuator_dw9714_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9714_camera.so:system/vendor/lib/libactuator_dw9714_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9714_q13v04b.so:system/vendor/lib/libactuator_dw9714_q13v04b.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9714_q13v04b_camcorder.so:system/vendor/lib/libacdbloader.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9714_q13v04b_camera.so:system/vendor/lib/libacdbloader.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9716.so:system/vendor/lib/libactuator_dw9716.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9716_camcorder.so:system/vendor/lib/libactuator_dw9716_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9716_camera.so:system/vendor/lib/libactuator_dw9716_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_iu074.so:system/vendor/lib/libactuator_iu074.so \
    $(PATH_FILES)/vendor/lib/libactuator_iu074_camcorder.so:system/vendor/lib/libactuator_iu074_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_iu074_camera.so:system/vendor/lib/libactuator_iu074_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov8825.so:system/vendor/lib/libactuator_ov8825.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov8825_camcorder.so:system/vendor/lib/libactuator_ov8825_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov8825_camera.so:system/vendor/lib/libactuator_ov8825_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov12830.so:system/vendor/lib/libactuator_ov12830.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov12830_camcorder.so:system/vendor/lib/libactuator_ov12830_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov12830_camera.so:system/vendor/lib/libactuator_ov12830_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_rohm_bu64243gwz.so:system/vendor/lib/libactuator_rohm_bu64243gwz.so \
    $(PATH_FILES)/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so:system/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_rohm_bu64243gwz_camera.so:system/vendor/lib/libactuator_rohm_bu64243gwz_camera.so \
    $(PATH_FILES)/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    $(PATH_FILES)/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    $(PATH_FILES)/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    $(PATH_FILES)/vendor/lib/libalarmservice_jni.so:system/vendor/lib/libalarmservice_jni.so \
    $(PATH_FILES)/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    $(PATH_FILES)/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
    $(PATH_FILES)/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    $(PATH_FILES)/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    $(PATH_FILES)/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    $(PATH_FILES)/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    $(PATH_FILES)/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    $(PATH_FILES)/vendor/lib/libcalmodule_akm.so:system/vendor/lib/libcalmodule_akm.so \
    $(PATH_FILES)/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    $(PATH_FILES)/vendor/lib/libchromatix_gc0339_alto45_common.so:system/vendor/lib/libchromatix_gc0339_alto45_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_gc0339_alto45_default_video.so:system/vendor/lib/libchromatix_gc0339_alto45_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_gc0339_alto45_preview.so:system/vendor/lib/libchromatix_gc0339_alto45_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_gc0339_alto45_snapshot.so:system/vendor/lib/libchromatix_gc0339_alto45_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_gc0339_sun_alto45_common.so:system/vendor/lib/libchromatix_gc0339_sun_alto45_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_gc0339_sun_alto45_default_video.so:system/vendor/lib/libchromatix_gc0339_sun_alto45_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_gc0339_sun_alto45_preview.so:system/vendor/lib/libchromatix_gc0339_sun_alto45_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_gc0339_sun_alto45_snapshot.so:system/vendor/lib/libchromatix_gc0339_sun_alto45_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx132_common.so:system/vendor/lib/libchromatix_imx132_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx132_default_video.so:system/vendor/lib/libchromatix_imx132_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx132_liveshot.so:system/vendor/lib/libchromatix_imx132_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx132_preview.so:system/vendor/lib/libchromatix_imx132_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx132_snapshot.so:system/vendor/lib/libchromatix_imx132_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx134_common.so:system/vendor/lib/libchromatix_imx134_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx134_default_video.so:system/vendor/lib/libchromatix_imx134_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx134_hfr_60.so:system/vendor/lib/libchromatix_imx134_hfr_60.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx134_hfr_120.so:system/vendor/lib/libchromatix_imx134_hfr_120.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx134_preview.so:system/vendor/lib/libchromatix_imx134_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx134_snapshot.so:system/vendor/lib/libchromatix_imx134_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx135_common.so:system/vendor/lib/libchromatix_imx135_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx135_default_video.so:system/vendor/lib/libchromatix_imx135_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx135_hfr_60.so:system/vendor/lib/libchromatix_imx135_hfr_60.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx135_hfr_90.so:system/vendor/lib/libchromatix_imx135_hfr_90.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx135_hfr_120.so:system/vendor/lib/libchromatix_imx135_hfr_120.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx135_preview.so:system/vendor/lib/libchromatix_imx135_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx135_snapshot.so:system/vendor/lib/libchromatix_imx135_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx135_video_hd.so:system/vendor/lib/libchromatix_imx135_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_5987fhq_common.so:system/vendor/lib/libchromatix_ov2680_5987fhq_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_5987fhq_default_video.so:system/vendor/lib/libchromatix_ov2680_5987fhq_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_5987fhq_preview.so:system/vendor/lib/libchromatix_ov2680_5987fhq_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_5987fhq_snapshot.so:system/vendor/lib/libchromatix_ov2680_5987fhq_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_common.so:system/vendor/lib/libchromatix_ov2680_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_default_video.so:system/vendor/lib/libchromatix_ov2680_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_preview.so:system/vendor/lib/libchromatix_ov2680_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_snapshot.so:system/vendor/lib/libchromatix_ov2680_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2720_common.so:system/vendor/lib/libchromatix_ov2720_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2720_default_video.so:system/vendor/lib/libchromatix_ov2720_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2720_hfr.so:system/vendor/lib/libchromatix_ov2720_hfr.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2720_liveshot.so:system/vendor/lib/libchromatix_ov2720_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2720_preview.so:system/vendor/lib/libchromatix_ov2720_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2720_zsl.so:system/vendor/lib/libchromatix_ov2720_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_oty5f03_common.so:system/vendor/lib/libchromatix_ov5648_oty5f03_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so:system/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_oty5f03_preview.so:system/vendor/lib/libchromatix_ov5648_oty5f03_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so:system/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so:system/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_p5v18g_common.so:system/vendor/lib/libchromatix_ov5648_p5v18g_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_p5v18g_default_video.so:system/vendor/lib/libchromatix_ov5648_p5v18g_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_p5v18g_default_video_hd.so:system/vendor/lib/libchromatix_ov5648_p5v18g_default_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_p5v18g_preview.so:system/vendor/lib/libchromatix_ov5648_p5v18g_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_p5v18g_snapshot.so:system/vendor/lib/libchromatix_ov5648_p5v18g_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_p5v18g_zsl.so:system/vendor/lib/libchromatix_ov5648_p5v18g_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_q5v22e_common.so:system/vendor/lib/libchromatix_ov5648_q5v22e_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_q5v22e_default_video.so:system/vendor/lib/libchromatix_ov5648_q5v22e_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_q5v22e_default_video_hd.so:system/vendor/lib/libchromatix_ov5648_q5v22e_default_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_q5v22e_preview.so:system/vendor/lib/libchromatix_ov5648_q5v22e_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_q5v22e_snapshot.so:system/vendor/lib/libchromatix_ov5648_q5v22e_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_q5v22e_zsl.so:system/vendor/lib/libchromatix_ov5648_q5v22e_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_alto45_common.so:system/vendor/lib/libchromatix_ov5670_alto45_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_alto45_default_video.so:system/vendor/lib/libchromatix_ov5670_alto45_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_alto45_hfr_60fps.so:system/vendor/lib/libchromatix_ov5670_alto45_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_alto45_hfr_90fps.so:system/vendor/lib/libchromatix_ov5670_alto45_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_alto45_hfr_120fps.so:system/vendor/lib/libchromatix_ov5670_alto45_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_alto45_preview.so:system/vendor/lib/libchromatix_ov5670_alto45_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_alto45_snapshot.so:system/vendor/lib/libchromatix_ov5670_alto45_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_alto45_video_hd.so:system/vendor/lib/libchromatix_ov5670_alto45_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_alto45_zsl.so:system/vendor/lib/libchromatix_ov5670_alto45_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_q5v41b_common.so:system/vendor/lib/libchromatix_ov5670_q5v41b_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_q5v41b_default_video.so:system/vendor/lib/libchromatix_ov5670_q5v41b_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_q5v41b_hfr_60fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_q5v41b_hfr_90fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_q5v41b_hfr_120fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_q5v41b_liveshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_q5v41b_preview.so:system/vendor/lib/libchromatix_ov5670_q5v41b_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_q5v41b_snapshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_q5v41b_video_hd.so:system/vendor/lib/libchromatix_ov5670_q5v41b_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_q5v41b_zsl.so:system/vendor/lib/libchromatix_ov5670_q5v41b_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_common.so:system/vendor/lib/libchromatix_ov8825_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_default_video.so:system/vendor/lib/libchromatix_ov8825_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_hfr_60fps.so:system/vendor/lib/libchromatix_ov8825_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_hfr_90fps.so:system/vendor/lib/libchromatix_ov8825_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_hfr_120fps.so:system/vendor/lib/libchromatix_ov8825_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_liveshot.so:system/vendor/lib/libchromatix_ov8825_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_liveshot_hd.so:system/vendor/lib/libchromatix_ov8825_liveshot_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_preview.so:system/vendor/lib/libchromatix_ov8825_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_preview_hd.so:system/vendor/lib/libchromatix_ov8825_preview_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_snapshot.so:system/vendor/lib/libchromatix_ov8825_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_snapshot_hd.so:system/vendor/lib/libchromatix_ov8825_snapshot_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_video_hd.so:system/vendor/lib/libchromatix_ov8825_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_zsl.so:system/vendor/lib/libchromatix_ov8825_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8865_q8v18a_common.so:system/vendor/lib/libchromatix_ov8865_q8v18a_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so:system/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8865_q8v18a_preview.so:system/vendor/lib/libchromatix_ov8865_q8v18a_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so:system/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so:system/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov9724_common.so:system/vendor/lib/libchromatix_ov9724_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov9724_default_video.so:system/vendor/lib/libchromatix_ov9724_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov9724_liveshot.so:system/vendor/lib/libchromatix_ov9724_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov9724_preview.so:system/vendor/lib/libchromatix_ov9724_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov13850_common.so:system/vendor/lib/libchromatix_ov13850_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov13850_default_video.so:system/vendor/lib/libchromatix_ov13850_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov13850_hfr_60fps.so:system/vendor/lib/libchromatix_ov13850_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov13850_hfr_90fps.so:system/vendor/lib/libchromatix_ov13850_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov13850_hfr_120fps.so:system/vendor/lib/libchromatix_ov13850_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov13850_preview.so:system/vendor/lib/libchromatix_ov13850_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov13850_snapshot.so:system/vendor/lib/libchromatix_ov13850_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k3l1yx_common.so:system/vendor/lib/libchromatix_s5k3l1yx_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k3l1yx_default_video.so:system/vendor/lib/libchromatix_s5k3l1yx_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k3l1yx_liveshot.so:system/vendor/lib/libchromatix_s5k3l1yx_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k3l1yx_preview.so:system/vendor/lib/libchromatix_s5k3l1yx_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k3l1yx_snapshot.so:system/vendor/lib/libchromatix_s5k3l1yx_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k3l1yx_video_hd.so:system/vendor/lib/libchromatix_s5k3l1yx_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k3l1yx_zsl.so:system/vendor/lib/libchromatix_s5k3l1yx_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k5e2_alto45_common.so:system/vendor/lib/libchromatix_s5k5e2_alto45_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k5e2_alto45_default_video.so:system/vendor/lib/libchromatix_s5k5e2_alto45_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k5e2_alto45_preview.so:system/vendor/lib/libchromatix_s5k5e2_alto45_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k5e2_alto45_snapshot.so:system/vendor/lib/libchromatix_s5k5e2_alto45_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_S5K4E1_13P1BA_common.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_S5K4E1_13P1BA_default_video.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_60fps.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_90fps.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_120fps.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_S5K4E1_13P1BA_liveshot.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_S5K4E1_13P1BA_preview.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_S5K4E1_13P1BA_snapshot.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_S5K4E1_13P1BA_video_hd.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_S5K4E1_13P1BA_zsl.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuab_shinetech_gc0339_liveshot.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuab_shinetech_gc0339_snapshot.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuab_shinetech_gc0339_zsl.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_video_hd.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_zsl.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_video_hd.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_zsl.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_zsl.so \
    $(PATH_FILES)/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    $(PATH_FILES)/vendor/lib/libcneconn.so:system/vendor/lib/libcneconn.so \
    $(PATH_FILES)/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
    $(PATH_FILES)/vendor/lib/libcneutils.so:system/vendor/lib/libcneutils.so \
    $(PATH_FILES)/vendor/lib/libCommandSvc.so:system/vendor/lib/libCommandSvc.so \
    $(PATH_FILES)/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    $(PATH_FILES)/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    $(PATH_FILES)/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
    $(PATH_FILES)/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    $(PATH_FILES)/vendor/lib/lib-dplmedia.so:system/vendor/lib/lib-dplmedia.so \
    $(PATH_FILES)/vendor/lib/libdpmctmgr.so:system/vendor/lib/libdpmctmgr.so \
    $(PATH_FILES)/vendor/lib/libdpmfdmgr.so:system/vendor/lib/libdpmfdmgr.so \
    $(PATH_FILES)/vendor/lib/libdpmframework.so:system/vendor/lib/libdpmframework.so \
    $(PATH_FILES)/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
    $(PATH_FILES)/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    $(PATH_FILES)/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    $(PATH_FILES)/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    $(PATH_FILES)/vendor/lib/libdsnetutils.so:system/vendor/lib/libdsnetutils.so \
    $(PATH_FILES)/vendor/lib/libdsucsd.so:system/vendor/lib/libdsucsd.so \
    $(PATH_FILES)/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    $(PATH_FILES)/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
    $(PATH_FILES)/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    $(PATH_FILES)/vendor/lib/libFileMux.so:system/vendor/lib/libFileMux.so \
    $(PATH_FILES)/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
    $(PATH_FILES)/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    $(PATH_FILES)/vendor/lib/libGPTEE.so:system/vendor/lib/libGPTEE.so \
    $(PATH_FILES)/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    $(PATH_FILES)/vendor/lib/libHevcSwDecoder.so:system/vendor/lib/libHevcSwDecoder.so \
    $(PATH_FILES)/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    $(PATH_FILES)/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    $(PATH_FILES)/vendor/lib/lib-imscamera.so:system/vendor/lib/lib-imscamera.so \
    $(PATH_FILES)/vendor/lib/lib-imsdpl.so:system/vendor/lib/lib-imsdpl.so \
    $(PATH_FILES)/vendor/lib/lib-imsqimf.so:system/vendor/lib/lib-imsqimf.so \
    $(PATH_FILES)/vendor/lib/lib-imsrcs.so:system/vendor/lib/lib-imsrcs.so \
    $(PATH_FILES)/vendor/lib/lib-imss.so:system/vendor/lib/lib-imss.so \
    $(PATH_FILES)/vendor/lib/lib-imsSDP.so:system/vendor/lib/lib-imsSDP.so \
    $(PATH_FILES)/vendor/lib/lib-imsvt.so:system/vendor/lib/lib-imsvt.so \
    $(PATH_FILES)/vendor/lib/lib-imsxml.so:system/vendor/lib/lib-imsxml.so \
    $(PATH_FILES)/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    $(PATH_FILES)/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    $(PATH_FILES)/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    $(PATH_FILES)/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    $(PATH_FILES)/vendor/lib/liblisten.so:system/vendor/lib/liblisten.so \
    $(PATH_FILES)/vendor/lib/liblistenhardware.so:system/vendor/lib/liblistenhardware.so \
    $(PATH_FILES)/vendor/lib/liblistenjni.so:system/vendor/lib/liblistenjni.so \
    $(PATH_FILES)/vendor/lib/liblistensoundmodel.so:system/vendor/lib/liblistensoundmodel.so \
    $(PATH_FILES)/vendor/lib/liblistensoundmodel2.so:system/vendor/lib/liblistensoundmodel2.so \
    $(PATH_FILES)/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    $(PATH_FILES)/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    $(PATH_FILES)/vendor/lib/libloc_ext.so:system/vendor/lib/libloc_ext.so \
    $(PATH_FILES)/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
    $(PATH_FILES)/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    $(PATH_FILES)/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
    $(PATH_FILES)/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_gc0339_alto45.so:system/vendor/lib/libmmcamera_gc0339_alto45.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_gc0339_sun_alto45.so:system/vendor/lib/libmmcamera_gc0339_sun_alto45.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_hi256.so:system/vendor/lib/libmmcamera_hi256.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_imx132.so:system/vendor/lib/libmmcamera_imx132.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_imx134.so:system/vendor/lib/libmmcamera_imx134.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_imx135.so:system/vendor/lib/libmmcamera_imx135.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_mt9m114.so:system/vendor/lib/libmmcamera_mt9m114.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so:system/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov2680.so:system/vendor/lib/libmmcamera_ov2680.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov2680_5987fhq.so:system/vendor/lib/libmmcamera_ov2680_5987fhq.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov2680_skuhf.so:system/vendor/lib/libmmcamera_ov2680_skuhf.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov2720.so:system/vendor/lib/libmmcamera_ov2720.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov5645.so:system/vendor/lib/libmmcamera_ov5645.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov5648_oty5f03.so:system/vendor/lib/libmmcamera_ov5648_oty5f03.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov5648_p5v18g.so:system/vendor/lib/libmmcamera_ov5648_p5v18g.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov5648_q5v22e.so:system/vendor/lib/libmmcamera_ov5648_q5v22e.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov5670_alto45.so:system/vendor/lib/libmmcamera_ov5670_alto45.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov5670_q5v41b.so:system/vendor/lib/libmmcamera_ov5670_q5v41b.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov8825.so:system/vendor/lib/libmmcamera_ov8825.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov8865_q8v18a.so:system/vendor/lib/libmmcamera_ov8865_q8v18a.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov9724.so:system/vendor/lib/libmmcamera_ov9724.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov13850.so:system/vendor/lib/libmmcamera_ov13850.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_s5k3l1yx.so:system/vendor/lib/libmmcamera_s5k3l1yx.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_s5k5e2_alto45.so:system/vendor/lib/libmmcamera_s5k5e2_alto45.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_S5K4E1_13P1BA.so:system/vendor/lib/libmmcamera_S5K4E1_13P1BA.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_S5K4E1_SKUHF.so:system/vendor/lib/libmmcamera_S5K4E1_SKUHF.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so:system/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so:system/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so:system/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so:system/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so:system/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_sp1628.so:system/vendor/lib/libmmcamera_sp1628.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so:system/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so:system/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_sunny_q5v22e_eeprom.so:system/vendor/lib/libmmcamera_sunny_q5v22e_eeprom.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_sunny_q5v41b_eeprom.so:system/vendor/lib/libmmcamera_sunny_q5v41b_eeprom.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so:system/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_sunny_q13v04b_eeprom.so:system/vendor/lib/libmmcamera_sunny_q13v04b_eeprom.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_truly_cm7700_eeprom.so:system/vendor/lib/libmmcamera_truly_cm7700_eeprom.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    $(PATH_FILES)/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    $(PATH_FILES)/vendor/lib/libmm-disp-apis.so:system/vendor/lib/libmm-disp-apis.so \
    $(PATH_FILES)/vendor/lib/libmm-hdcpmgr.so:system/vendor/lib/libmm-hdcpmgr.so \
    $(PATH_FILES)/vendor/lib/libmmhttpstack.so:system/vendor/lib/libmmhttpstack.so \
    $(PATH_FILES)/vendor/lib/libmmi.so:system/vendor/lib/libmmi.so \
    $(PATH_FILES)/vendor/lib/libmmiipstreammmihttp.so:system/vendor/lib/libmmiipstreammmihttp.so \
    $(PATH_FILES)/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    $(PATH_FILES)/vendor/lib/libmmipstreamaal.so:system/vendor/lib/libmmipstreamaal.so \
    $(PATH_FILES)/vendor/lib/libmmipstreamnetwork.so:system/vendor/lib/libmmipstreamnetwork.so \
    $(PATH_FILES)/vendor/lib/libmmipstreamsourcehttp.so:system/vendor/lib/libmmipstreamsourcehttp.so \
    $(PATH_FILES)/vendor/lib/libmmipstreamutils.so:system/vendor/lib/libmmipstreamutils.so \
    $(PATH_FILES)/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    $(PATH_FILES)/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    $(PATH_FILES)/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
    $(PATH_FILES)/vendor/lib/libmm-qdcm.so:system/vendor/lib/libmm-qdcm.so \
    $(PATH_FILES)/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    $(PATH_FILES)/vendor/lib/libmmQSM.so:system/vendor/lib/libmmQSM.so \
    $(PATH_FILES)/vendor/lib/libmmQTA.so:system/vendor/lib/libmmQTA.so \
    $(PATH_FILES)/vendor/lib/libmmrtpdecoder.so:system/vendor/lib/libmmrtpdecoder.so \
    $(PATH_FILES)/vendor/lib/libmmrtpencoder.so:system/vendor/lib/libmmrtpencoder.so \
    $(PATH_FILES)/vendor/lib/libmmwfdinterface.so:system/vendor/lib/libmmwfdinterface.so \
    $(PATH_FILES)/vendor/lib/libmmwfdsinkinterface.so:system/vendor/lib/libmmwfdsinkinterface.so \
    $(PATH_FILES)/vendor/lib/libmmwfdsrcinterface.so:system/vendor/lib/libmmwfdsrcinterface.so \
    $(PATH_FILES)/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    $(PATH_FILES)/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
    $(PATH_FILES)/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    $(PATH_FILES)/vendor/lib/liboi_sbc_decoder.so:system/vendor/lib/liboi_sbc_decoder.so \
    $(PATH_FILES)/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    $(PATH_FILES)/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    $(PATH_FILES)/vendor/lib/libOmxMux.so:system/vendor/lib/libOmxMux.so \
    $(PATH_FILES)/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    $(PATH_FILES)/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    $(PATH_FILES)/vendor/lib/libprdrmdecrypt.so:system/vendor/lib/libprdrmdecrypt.so \
    $(PATH_FILES)/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    $(PATH_FILES)/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
    $(PATH_FILES)/vendor/lib/libqct_resampler.so:system/vendor/lib/libqct_resampler.so \
    $(PATH_FILES)/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    $(PATH_FILES)/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    $(PATH_FILES)/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    $(PATH_FILES)/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    $(PATH_FILES)/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    $(PATH_FILES)/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    $(PATH_FILES)/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    $(PATH_FILES)/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    $(PATH_FILES)/vendor/lib/libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so \
    $(PATH_FILES)/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    $(PATH_FILES)/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    $(PATH_FILES)/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    $(PATH_FILES)/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    $(PATH_FILES)/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    $(PATH_FILES)/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    $(PATH_FILES)/vendor/lib/lib-rcsimssjni.so:system/vendor/lib/lib-rcsimssjni.so \
    $(PATH_FILES)/vendor/lib/lib-rcsjni.so:system/vendor/lib/lib-rcsjni.so \
    $(PATH_FILES)/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    $(PATH_FILES)/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    $(PATH_FILES)/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    $(PATH_FILES)/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    $(PATH_FILES)/vendor/lib/lib-rtpcommon.so:system/vendor/lib/lib-rtpcommon.so \
    $(PATH_FILES)/vendor/lib/lib-rtpcore.so:system/vendor/lib/lib-rtpcore.so \
    $(PATH_FILES)/vendor/lib/lib-rtpdaemoninterface.so:system/vendor/lib/lib-rtpdaemoninterface.so \
    $(PATH_FILES)/vendor/lib/lib-rtpsl.so:system/vendor/lib/lib-rtpsl.so \
    $(PATH_FILES)/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
    $(PATH_FILES)/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    $(PATH_FILES)/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    $(PATH_FILES)/vendor/lib/libsd_sdk_display.so:system/vendor/lib/libsd_sdk_display.so \
    $(PATH_FILES)/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
    $(PATH_FILES)/vendor/lib/libsrsprocessing.so:system/vendor/lib/libsrsprocessing.so \
    $(PATH_FILES)/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    $(PATH_FILES)/vendor/lib/libsubsystem_control.so:system/vendor/lib/libsubsystem_control.so \
    $(PATH_FILES)/vendor/lib/libSubSystemShutdown.so:system/vendor/lib/libSubSystemShutdown.so \
    $(PATH_FILES)/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    $(PATH_FILES)/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
    $(PATH_FILES)/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    $(PATH_FILES)/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    $(PATH_FILES)/vendor/lib/libtzdrmgenprov.so:system/vendor/lib/libtzdrmgenprov.so \
    $(PATH_FILES)/vendor/lib/libtzplayready.so:system/vendor/lib/libtzplayready.so \
    $(PATH_FILES)/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    $(PATH_FILES)/vendor/lib/libvoice-svc.so:system/vendor/lib/libvoice-svc.so \
    $(PATH_FILES)/vendor/lib/libwfdcommonutils.so:system/vendor/lib/libwfdcommonutils.so \
    $(PATH_FILES)/vendor/lib/libwfdhdcpcp.so:system/vendor/lib/libwfdhdcpcp.so \
    $(PATH_FILES)/vendor/lib/libwfdmmsink.so:system/vendor/lib/libwfdmmsink.so \
    $(PATH_FILES)/vendor/lib/libwfdmmsrc.so:system/vendor/lib/libwfdmmsrc.so \
    $(PATH_FILES)/vendor/lib/libwfdmmutils.so:system/vendor/lib/libwfdmmutils.so \
    $(PATH_FILES)/vendor/lib/libwfdnative.so:system/vendor/lib/libwfdnative.so \
    $(PATH_FILES)/vendor/lib/libwfdrtsp.so:system/vendor/lib/libwfdrtsp.so \
    $(PATH_FILES)/vendor/lib/libwfdsm.so:system/vendor/lib/libwfdsm.so \
    $(PATH_FILES)/vendor/lib/libwfduibcinterface.so:system/vendor/lib/libwfduibcinterface.so \
    $(PATH_FILES)/vendor/lib/libwfduibcsink.so:system/vendor/lib/libwfduibcsink.so \
    $(PATH_FILES)/vendor/lib/libwfduibcsinkinterface.so:system/vendor/lib/libwfduibcsinkinterface.so \
    $(PATH_FILES)/vendor/lib/libwfduibcsrc.so:system/vendor/lib/libwfduibcsrc.so \
    $(PATH_FILES)/vendor/lib/libwfduibcsrcinterface.so:system/vendor/lib/libwfduibcsrcinterface.so \
    $(PATH_FILES)/vendor/lib/libwifiscanner.so:system/vendor/lib/libwifiscanner.so \
    $(PATH_FILES)/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    $(PATH_FILES)/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    $(PATH_FILES)/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    $(PATH_FILES)/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    $(PATH_FILES)/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
    $(PATH_FILES)/vendor/lib/libxt_native.so:system/vendor/lib/libxt_native.so \
    $(PATH_FILES)/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
    $(PATH_FILES)/vendor/lib/libxtwifi_zpp_adaptor.so:system/vendor/lib/libxtwifi_zpp_adaptor.so \
    $(PATH_FILES)/vendor/lib/mmi_audio.so:system/vendor/lib/mmi_audio.so \
    $(PATH_FILES)/vendor/lib/mmi_battery.so:system/vendor/lib/mmi_battery.so \
    $(PATH_FILES)/vendor/lib/mmi_bt.so:system/vendor/lib/mmi_bt.so \
    $(PATH_FILES)/vendor/lib/mmi_camera.so:system/vendor/lib/mmi_camera.so \
    $(PATH_FILES)/vendor/lib/mmi_flashlight.so:system/vendor/lib/mmi_flashlight.so \
    $(PATH_FILES)/vendor/lib/mmi_fm.so:system/vendor/lib/mmi_fm.so \
    $(PATH_FILES)/vendor/lib/mmi_gps_garden.so:system/vendor/lib/mmi_gps_garden.so \
    $(PATH_FILES)/vendor/lib/mmi_gsensor.so:system/vendor/lib/mmi_gsensor.so \
    $(PATH_FILES)/vendor/lib/mmi_gyroscope.so:system/vendor/lib/mmi_gyroscope.so \
    $(PATH_FILES)/vendor/lib/mmi_key.so:system/vendor/lib/mmi_key.so \
    $(PATH_FILES)/vendor/lib/mmi_keypadbacklight.so:system/vendor/lib/mmi_keypadbacklight.so \
    $(PATH_FILES)/vendor/lib/mmi_lcd.so:system/vendor/lib/mmi_lcd.so \
    $(PATH_FILES)/vendor/lib/mmi_led.so:system/vendor/lib/mmi_led.so \
    $(PATH_FILES)/vendor/lib/mmi_lsensor.so:system/vendor/lib/mmi_lsensor.so \
    $(PATH_FILES)/vendor/lib/mmi_msensor.so:system/vendor/lib/mmi_msensor.so \
    $(PATH_FILES)/vendor/lib/mmi_psensor.so:system/vendor/lib/mmi_psensor.so \
    $(PATH_FILES)/vendor/lib/mmi_sdcard.so:system/vendor/lib/mmi_sdcard.so \
    $(PATH_FILES)/vendor/lib/mmi_sim.so:system/vendor/lib/mmi_sim.so \
    $(PATH_FILES)/vendor/lib/mmi_sysinfo.so:system/vendor/lib/mmi_sysinfo.so \
    $(PATH_FILES)/vendor/lib/mmi_touch.so:system/vendor/lib/mmi_touch.so \
    $(PATH_FILES)/vendor/lib/mmi_touchpanel.so:system/vendor/lib/mmi_touchpanel.so \
    $(PATH_FILES)/vendor/lib/mmi_vibrator.so:system/vendor/lib/mmi_vibrator.so \
    $(PATH_FILES)/vendor/lib/mmi_volume.so:system/vendor/lib/mmi_volume.so \
    $(PATH_FILES)/vendor/lib/mmi_wifi.so:system/vendor/lib/mmi_wifi.so
